### ISSUE TITLE
Project not generated properly

### ISSUE THREAD

**Issue by klawr** [deeplex/copier-cpp-library#2]
**Describe the bug**
After generating a test using the template some files still have the `.jinja` files extension
Affected files are:
 - .editorconfig
 - {{_copier_conf.answers_file}}.jinja (should this exist at all in the generated project?)
 - CMakeLists.txt
 - README.rst
 - sources.cmake
 - vcpkg.json

Other paths which do not look right are:
 - `tools/{{project_slug}}-config.cmake.in.jinja`
 - `src/{{namespace}}_tests/test_utils.hpp.jinja`
 - `docs/conf.py.jinja`
 - `docs/index.rst.jinja`
 - `docs/html.jinja`

**To Reproduce**
Install copier using
`pipx install copier`
Fix https://github.com/Tecnativa/doodba-copier-template/issues/323 by running
`pip install --force-reinstall MarkupSafe==2.0.1`
Run
`copier https://github.com/deeplex/copier-cpp-library.git ./test`

**Expected behavior**
Files without fragments and without `.jinja` extension

**Screenshots**
root:
![image](https://user-images.githubusercontent.com/16281695/163709171-514dfe27-91a4-4d5f-9e57-8a8b988e4cd4.png)
docs:
![image](https://user-images.githubusercontent.com/16281695/163709296-cde08c2c-d19e-44d0-b2e8-3cc179ce8e6c.png)

**Environment**
 - OS: Windows 10
 - Project Version: 4c5df3dca61709623d26c333708c98374a66ba93

**Additional context**
Nope

**Comment by BurningEnlightenment** [comment]
try again after running `pip install copier==v6.0.0b0`

**Comment by klawr** [comment]
Seems to be working fine.
Reinstalled copier to confirm that `pip install copier` installs `copier==5.1.0`.
Will add necessary documentation to [the main documentation](docs.deeplex.net)
